DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS sprinkler;
DROP TABLE IF EXISTS circuit;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE circuit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    number INTEGER UNIQUE
);

CREATE TABLE sprinkler (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  number INTEGER UNIQUE,
  x DOUBLE DEFAULT 0,
  y DOUBLE DEFAULT 0,
  circuit_id INTEGER NOT NULL,
  FOREIGN KEY (circuit_id) REFERENCES circuit (id)
);

CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  start DATETIME NOT NULL,
  duration INTEGER NOT NULL,
  circuit_id INTEGER NOT NULL,
  FOREIGN KEY (circuit_id) REFERENCES sprinkler (id)
);